### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by tfels** [tfels/ConnectTC66C#4]
### ToDo List

- [x] choose BT device in list
- [x] save choosen BT device to preferences
- [x] auto connect to last used BT device on startup
- [ ] ~pass BT object from activity to fragment via bundle instead of direct class method call~
- [x] PoC UI for sending different comands
- [ ] split BT handling class: 1. generic BT stuff, 2. TC66 specific GATT comminucation
- [ ] move permission check to generic BT class
- [ ] re-check BT error handling / internal state variable
- [x] implement reading data from device

**Comment by tfels** [comment]
moved issues to separate tickets
